spring.application.name=Load Balancer Service

# RabbitMQ connection
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Input queue from simulator
loadbalancer.input-queue=simulator.data.queue

# Output queues for monitoring replicas (comma-separated)
loadbalancer.output-queues=monitoring.ingestion.queue.1,monitoring.ingestion.queue.2,monitoring.ingestion.queue.3

# Number of replicas
loadbalancer.replica-count=3

server.port=${PORT:8085}
