spring.application.name=Device Data Simulator

# RabbitMQ connection  #rabitmq
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange / queue / routing key - sends to load balancer input queue
simulator.queue=simulator.data.queue


# Simulator parameters - multiple device IDs (comma-separated)
simulator.device-ids=50f791d6-3734-400a-9eab-1d73bf5d89c5,b5880821-fb6c-4165-9540-0a2316971a05,814f794c-8f89-4699-9885-8c2ae6098b51
# e.g. 6 * 10min = 1h
simulator.readings-count=144
# logical interval between readings
simulator.interval-minutes=10
# or Europe/Bucharest etc.
simulator.timezone=UTC