spring.application.name=Device Data Simulator

# RabbitMQ connection  #rabitmq
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange / queue / routing key - sends to load balancer input queue
simulator.queue=simulator.data.queue


# Simulator parameters - multiple device IDs (comma-separated)
simulator.device-ids=a53c6aac-80ac-4a1f-81fc-9e2d8634f037,c0e6d4ca-35a6-48ed-a404-9d4c47173e95,0085d227-9aa0-4180-b316-2f62acbd64a0
# e.g. 6 * 10min = 1h
simulator.readings-count=144
# logical interval between readings
simulator.interval-minutes=10
# or Europe/Bucharest etc.
simulator.timezone=UTC